Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

# generate data
np.random.seed(0)
loc = 10
scale = 2
n_iter = 10000
results = []
for n in [10, 100, 1000]:
    means = []
    errors = []
    for i_iter in range(n_iter):
        samples = np.random.normal(loc=loc, scale=scale, size=n)
        # 標本平均 \bar{X}
        means.append(samples.mean())
        # 標準化した推定誤差
        mu_hat = samples.mean()
        error = np.sqrt(n) * (mu_hat - mu)
        errors.append(error)
    results.append({
        "n": n,
        "means": means,
        "errors": errors
    })

# plot
fig, ax = plt.subplots()
for result in results:
    n = result["n"]
    means = result["means"]
    ax.hist(means, label=f"{n=} mean={np.mean(means):.1f} s.e.={np.std(means):.2f} | " + r"estimate $\sigma/\sqrt{n}$" + f"={scale/np.sqrt(n):.2f}", alpha=0.7, bins=30)
ax.legend()
ax.set(xlabel=r"$\bar{X}$", title=fr"distribution of sample mean $\bar X$ ($X \sim N$({loc}, {scale**2}))")
fig.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 19[0m
[1;32m     17[0m     [38;5;66;03m# 標準化した推定誤差[39;00m
[1;32m     18[0m     mu_hat [38;5;241m=[39m samples[38;5;241m.[39mmean()
[0;32m---> 19[0m     error [38;5;241m=[39m np[38;5;241m.[39msqrt(n) [38;5;241m*[39m (mu_hat [38;5;241m-[39m [43mmu[49m)
[1;32m     20[0m     errors[38;5;241m.[39mappend(error)
[1;32m     21[0m results[38;5;241m.[39mappend({
[1;32m     22[0m     [38;5;124m"[39m[38;5;124mn[39m[38;5;124m"[39m: n,
[1;32m     23[0m     [38;5;124m"[39m[38;5;124mmeans[39m[38;5;124m"[39m: means,
[1;32m     24[0m     [38;5;124m"[39m[38;5;124merrors[39m[38;5;124m"[39m: errors
[1;32m     25[0m })

[0;31mNameError[0m: name 'mu' is not defined

