Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

w = 0.3
N = 100
x1 = norm.rvs(loc=0, scale=1, size=n, random_state=0)
x2 = w * x1 + (1 - w) * norm.rvs(loc=0, scale=1, size=N, random_state=1)
X = np.append(x1.reshape(-1, 1), x2.reshape(-1, 1), axis=1)

fig, ax = plt.subplots()
ax.scatter(x1, x2)
ax.set(xlabel="x1", ylabel="x2")
fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 7[0m
[1;32m      5[0m w [38;5;241m=[39m [38;5;241m0.3[39m
[1;32m      6[0m N [38;5;241m=[39m [38;5;241m100[39m
[0;32m----> 7[0m x1 [38;5;241m=[39m norm[38;5;241m.[39mrvs(loc[38;5;241m=[39m[38;5;241m0[39m, scale[38;5;241m=[39m[38;5;241m1[39m, size[38;5;241m=[39m[43mn[49m, random_state[38;5;241m=[39m[38;5;241m0[39m)
[1;32m      8[0m x2 [38;5;241m=[39m w [38;5;241m*[39m x1 [38;5;241m+[39m ([38;5;241m1[39m [38;5;241m-[39m w) [38;5;241m*[39m norm[38;5;241m.[39mrvs(loc[38;5;241m=[39m[38;5;241m0[39m, scale[38;5;241m=[39m[38;5;241m1[39m, size[38;5;241m=[39mN, random_state[38;5;241m=[39m[38;5;241m1[39m)
[1;32m      9[0m X [38;5;241m=[39m np[38;5;241m.[39mappend(x1[38;5;241m.[39mreshape([38;5;241m-[39m[38;5;241m1[39m, [38;5;241m1[39m), x2[38;5;241m.[39mreshape([38;5;241m-[39m[38;5;241m1[39m, [38;5;241m1[39m), axis[38;5;241m=[39m[38;5;241m1[39m)

[0;31mNameError[0m: name 'n' is not defined
NameError: name 'n' is not defined

