Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# nest_asyncio: asyncio„Çí‰Ωø„ÅÜstan„Çíjupyter„Åß‰Ωø„ÅÜ„Åü„ÇÅ„ÅÆÂØæÂá¶
import nest_asyncio
nest_asyncio.apply()

import stan

stan_code = """
data {
    int N;
    real X[N];
}
parameters {
    real<lower=0> n;
    real<lower=0, upper=1> p;
}
model {
    X ~ bernoulli(p);
}
"""

data = {
    "N": len(x),
    "X": x,
}

posterior = stan.build(stan_code, data=data, random_seed=1)
fit = posterior.sample(num_chains=4, num_samples=100)
df = fit.to_frame()
df
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 26>[0;34m()[0m
[1;32m      7[0m stan_code [38;5;241m=[39m [38;5;124m"""[39m
[1;32m      8[0m [38;5;124mdata [39m[38;5;124m{[39m
[1;32m      9[0m [38;5;124m    int N;[39m
[0;32m   (...)[0m
[1;32m     18[0m [38;5;124m}[39m
[1;32m     19[0m [38;5;124m"""[39m
[1;32m     21[0m data [38;5;241m=[39m {
[1;32m     22[0m     [38;5;124m"[39m[38;5;124mN[39m[38;5;124m"[39m: [38;5;28mlen[39m(x),
[1;32m     23[0m     [38;5;124m"[39m[38;5;124mX[39m[38;5;124m"[39m: x,
[1;32m     24[0m }
[0;32m---> 26[0m posterior [38;5;241m=[39m [43mstan[49m[38;5;241;43m.[39;49m[43mbuild[49m[43m([49m[43mstan_code[49m[43m,[49m[43m [49m[43mdata[49m[38;5;241;43m=[39;49m[43mdata[49m[43m,[49m[43m [49m[43mrandom_seed[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m)[49m
[1;32m     27[0m fit [38;5;241m=[39m posterior[38;5;241m.[39msample(num_chains[38;5;241m=[39m[38;5;241m4[39m, num_samples[38;5;241m=[39m[38;5;241m100[39m)
[1;32m     28[0m df [38;5;241m=[39m fit[38;5;241m.[39mto_frame()

File [0;32m/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/stan/model.py:518[0m, in [0;36mbuild[0;34m(program_code, data, random_seed)[0m
[1;32m    515[0m         [38;5;28;01mreturn[39;00m Model(model_name, program_code, data, param_names, constrained_param_names, dims, random_seed)
[1;32m    517[0m [38;5;28;01mtry[39;00m:
[0;32m--> 518[0m     [38;5;28;01mreturn[39;00m [43masyncio[49m[38;5;241;43m.[39;49m[43mrun[49m[43m([49m[43mgo[49m[43m([49m[43m)[49m[43m)[49m
[1;32m    519[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyboardInterrupt[39;00m:
[1;32m    520[0m     [38;5;28;01mreturn[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nest_asyncio.py:35[0m, in [0;36m_patch_asyncio.<locals>.run[0;34m(main, debug)[0m
[1;32m     33[0m task [38;5;241m=[39m asyncio[38;5;241m.[39mensure_future(main)
[1;32m     34[0m [38;5;28;01mtry[39;00m:
[0;32m---> 35[0m     [38;5;28;01mreturn[39;00m [43mloop[49m[38;5;241;43m.[39;49m[43mrun_until_complete[49m[43m([49m[43mtask[49m[43m)[49m
[1;32m     36[0m [38;5;28;01mfinally[39;00m:
[1;32m     37[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m task[38;5;241m.[39mdone():

File [0;32m/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nest_asyncio.py:89[0m, in [0;36m_patch_loop.<locals>.run_until_complete[0;34m(self, future)[0m
[1;32m     86[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m f[38;5;241m.[39mdone():
[1;32m     87[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(
[1;32m     88[0m         [38;5;124m'[39m[38;5;124mEvent loop stopped before Future completed.[39m[38;5;124m'[39m)
[0;32m---> 89[0m [38;5;28;01mreturn[39;00m [43mf[49m[38;5;241;43m.[39;49m[43mresult[49m[43m([49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/asyncio/futures.py:201[0m, in [0;36mFuture.result[0;34m(self)[0m
[1;32m    199[0m [38;5;28mself[39m[38;5;241m.[39m__log_traceback [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    200[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_exception [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 201[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39m_exception
[1;32m    202[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_result

File [0;32m/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/asyncio/tasks.py:256[0m, in [0;36mTask.__step[0;34m(***failed resolving arguments***)[0m
[1;32m    252[0m [38;5;28;01mtry[39;00m:
[1;32m    253[0m     [38;5;28;01mif[39;00m exc [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    254[0m         [38;5;66;03m# We use the `send` method directly, because coroutines[39;00m
[1;32m    255[0m         [38;5;66;03m# don't have `__iter__` and `__next__` methods.[39;00m
[0;32m--> 256[0m         result [38;5;241m=[39m [43mcoro[49m[38;5;241;43m.[39;49m[43msend[49m[43m([49m[38;5;28;43;01mNone[39;49;00m[43m)[49m
[1;32m    257[0m     [38;5;28;01melse[39;00m:
[1;32m    258[0m         result [38;5;241m=[39m coro[38;5;241m.[39mthrow(exc)

File [0;32m/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/stan/model.py:497[0m, in [0;36mbuild.<locals>.go[0;34m()[0m
[1;32m    495[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(error_type)
[1;32m    496[0m     [38;5;28;01melse[39;00m:
[0;32m--> 497[0m         [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(exception_body)
[1;32m    498[0m building_output[38;5;241m.[39mclear() [38;5;28;01mif[39;00m io[38;5;241m.[39msupports_ansi() [38;5;28;01melse[39;00m building_output[38;5;241m.[39mwrite([38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m)
[1;32m    499[0m [38;5;28;01mif[39;00m model_in_cache:

[0;31mRuntimeError[0m: Warning in '/tmp/httpstan_wlavuu7x/model_3h2sbrlq.stan', line 4, column 4: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Semantic error in '/tmp/httpstan_wlavuu7x/model_3h2sbrlq.stan', line 11, column 4 to column 21:
   -------------------------------------------------
     9:  }
    10:  model {
    11:      X ~ bernoulli(p);
             ^
    12:  }
   -------------------------------------------------

Ill-typed arguments supplied to function 'bernoulli':
(array[] real, real)
Available signatures:
(int, row_vector) => real
  The first argument must be int but got array[] real
(int, vector) => real
  The first argument must be int but got array[] real
(int, array[] real) => real
  The first argument must be int but got array[] real
(int, real) => real
  The first argument must be int but got array[] real
(array[] int, row_vector) => real
  The first argument must be array[] int but got array[] real
(Additional signatures omitted)
RuntimeError: Warning in '/tmp/httpstan_wlavuu7x/model_3h2sbrlq.stan', line 4, column 4: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Semantic error in '/tmp/httpstan_wlavuu7x/model_3h2sbrlq.stan', line 11, column 4 to column 21:
   -------------------------------------------------
     9:  }
    10:  model {
    11:      X ~ bernoulli(p);
             ^
    12:  }
   -------------------------------------------------

Ill-typed arguments supplied to function 'bernoulli':
(array[] real, real)
Available signatures:
(int, row_vector) => real
  The first argument must be int but got array[] real
(int, vector) => real
  The first argument must be int but got array[] real
(int, array[] real) => real
  The first argument must be int but got array[] real
(int, real) => real
  The first argument must be int but got array[] real
(array[] int, row_vector) => real
  The first argument must be array[] int but got array[] real
(Additional signatures omitted)

