Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# 識別境界を簡単に描画

# 格子状のデータ点
import numpy as np
from itertools import product

x0 = np.arange(X[:, 0].min(), X[:, 0].max(), 0.1)
x1 = np.arange(X[:, 1].min(), X[:, 1].max(), 0.1)
X_grid = np.array(list(product(x0, x1)))

# 予測
y_pred = np.array([predict(x) for x in X_grid])

# plot
fig, ax = plt.subplots()
# datapoints
for label in np.unique(y):
    idx = y == label
    ax.scatter(X[idx, 0], X[idx, 1], label=f"y={label}")

# prediction
for label in np.unique(y_pred):
    idx = y_pred == label
    ax.scatter(X_grid[idx, 0], X_grid[idx, 1], label=f"y_pred={label}", alpha=0.2)
ax.legend()
fig.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 12[0m
[1;32m      9[0m X_grid [38;5;241m=[39m np[38;5;241m.[39marray([38;5;28mlist[39m(product(x0, x1)))
[1;32m     11[0m [38;5;66;03m# 予測[39;00m
[0;32m---> 12[0m y_pred [38;5;241m=[39m np[38;5;241m.[39marray([predict(x) [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m X_grid])
[1;32m     14[0m [38;5;66;03m# plot[39;00m
[1;32m     15[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()

Cell [0;32mIn[3], line 12[0m, in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m      9[0m X_grid [38;5;241m=[39m np[38;5;241m.[39marray([38;5;28mlist[39m(product(x0, x1)))
[1;32m     11[0m [38;5;66;03m# 予測[39;00m
[0;32m---> 12[0m y_pred [38;5;241m=[39m np[38;5;241m.[39marray([[43mpredict[49m[43m([49m[43mx[49m[43m)[49m [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m X_grid])
[1;32m     14[0m [38;5;66;03m# plot[39;00m
[1;32m     15[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()

Cell [0;32mIn[2], line 5[0m, in [0;36mpredict[0;34m(x_test)[0m
[1;32m      3[0m [38;5;28;01mdef[39;00m [38;5;21mpredict[39m(x_test: np[38;5;241m.[39marray) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mint[39m:
[1;32m      4[0m     [38;5;66;03m# testのデータ点と訓練データの点の距離[39;00m
[0;32m----> 5[0m     distances [38;5;241m=[39m np[38;5;241m.[39mlinalg[38;5;241m.[39mnorm([43mX_train[49m [38;5;241m-[39m x_test, axis[38;5;241m=[39m[38;5;241m1[39m)
[1;32m      6[0m     neighbors_idx [38;5;241m=[39m np[38;5;241m.[39margsort(distances)[:k]
[1;32m      7[0m     neighbors [38;5;241m=[39m y_train[neighbors_idx]

[0;31mNameError[0m: name 'X_train' is not defined

