Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import cmath
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(4, 3))
ax.set_aspect('equal', 'box')

# 軸を描画
ax.arrow(-1.2, 0, 2.4, 0, head_width=0.05, head_length=0.1, fc='black', ec='black', length_includes_head=True)
ax.arrow(0, -1.2, 0, 2.4, head_width=0.05, head_length=0.1, fc='black', ec='black', length_includes_head=True)

ax.text(1.3, 0, "1", fontsize=14, color='black')
ax.text(0, 1.3, "i", fontsize=14, color='black')

ax.set_aspect('equal', adjustable='datalim')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_visible(False)
ax.spines['bottom'].set_visible(False)
ax.set(xticks=[], yticks=[])
ax.set(xlim=(-1.2, 1.2), ylim=(-1.2, 1.2))

# 単位円
unit_circle = plt.Circle((0, 0), 1, color='gray', fill=False)
ax.add_artist(unit_circle)

# 偶数のN
n = 10
omega_n = cmath.exp(2j * cmath.pi / n)

ax.plot([0, omega_n.real], [0, omega_n.imag], color="gray", linestyle='-', linewidth=0.8)
t = 2 * np.pi / n
theta = np.linspace(0, t, 100)
x = np.cos(theta) * 0.2
y = np.sin(theta) * 0.2
ax.plot(x, y, color="gray", linewidth=1)

for k in range(n):
    omega = omega_n**k
    ax.plot(omega.real, omega.imag, 'o', color="gray")
    ax.text(omega.real + 0.02, omega.imag + 0.02, rf'$\omega_N^{k}$', fontsize=10, color="dimgray", ha='left')

plt.show()
------------------

----- stderr -----
Ignoring fixed x limits to fulfill fixed data aspect with adjustable data limits.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 31[0m
[1;32m     28[0m omega_n [38;5;241m=[39m cmath[38;5;241m.[39mexp([38;5;241m2[39mj [38;5;241m*[39m cmath[38;5;241m.[39mpi [38;5;241m/[39m n)
[1;32m     30[0m ax[38;5;241m.[39mplot([[38;5;241m0[39m, omega_n[38;5;241m.[39mreal], [[38;5;241m0[39m, omega_n[38;5;241m.[39mimag], color[38;5;241m=[39m[38;5;124m"[39m[38;5;124mgray[39m[38;5;124m"[39m, linestyle[38;5;241m=[39m[38;5;124m'[39m[38;5;124m-[39m[38;5;124m'[39m, linewidth[38;5;241m=[39m[38;5;241m0.8[39m)
[0;32m---> 31[0m t [38;5;241m=[39m [38;5;241m2[39m [38;5;241m*[39m [43mnp[49m[38;5;241m.[39mpi [38;5;241m/[39m n
[1;32m     32[0m theta [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m, t, [38;5;241m100[39m)
[1;32m     33[0m x [38;5;241m=[39m np[38;5;241m.[39mcos(theta) [38;5;241m*[39m [38;5;241m0.2[39m

[0;31mNameError[0m: name 'np' is not defined

