Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import time
import pandas as pd
import numpy as np
from surprise import Dataset, Reader, accuracy
from surprise.model_selection import train_test_split
from surprise import SVD, NMF
------------------

----- stderr -----

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/usr/local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "/usr/local/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_13840/1423974185.py", line 4, in <module>
    from surprise import Dataset, Reader, accuracy
  File "/usr/local/lib/python3.10/site-packages/surprise/__init__.py", line 6, in <module>
    from .prediction_algorithms import (
  File "/usr/local/lib/python3.10/site-packages/surprise/prediction_algorithms/__init__.py", line 23, in <module>
    from .algo_base import AlgoBase
  File "/usr/local/lib/python3.10/site-packages/surprise/prediction_algorithms/algo_base.py", line 8, in <module>
    from .. import similarities as sims
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 4[0m
[1;32m      2[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mpandas[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mpd[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mnumpy[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mnp[39;00m
[0;32m----> 4[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01msurprise[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Dataset, Reader, accuracy
[1;32m      5[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01msurprise[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodel_selection[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m train_test_split
[1;32m      6[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01msurprise[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m SVD, NMF

File [0;32m/usr/local/lib/python3.10/site-packages/surprise/__init__.py:6[0m
[1;32m      2[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mbuiltin_datasets[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m get_dataset_dir
[1;32m      4[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mdataset[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Dataset
[0;32m----> 6[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mprediction_algorithms[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m (
[1;32m      7[0m     AlgoBase,
[1;32m      8[0m     BaselineOnly,
[1;32m      9[0m     CoClustering,
[1;32m     10[0m     KNNBaseline,
[1;32m     11[0m     KNNBasic,
[1;32m     12[0m     KNNWithMeans,
[1;32m     13[0m     KNNWithZScore,
[1;32m     14[0m     NMF,
[1;32m     15[0m     NormalPredictor,
[1;32m     16[0m     Prediction,
[1;32m     17[0m     PredictionImpossible,
[1;32m     18[0m     SlopeOne,
[1;32m     19[0m     SVD,
[1;32m     20[0m     SVDpp,
[1;32m     21[0m )
[1;32m     22[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mreader[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Reader
[1;32m     23[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mtrainset[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Trainset

File [0;32m/usr/local/lib/python3.10/site-packages/surprise/prediction_algorithms/__init__.py:23[0m
[1;32m      1[0m [38;5;124;03m"""[39;00m
[1;32m      2[0m [38;5;124;03mThe :mod:`prediction_algorithms` package includes the prediction algorithms[39;00m
[1;32m      3[0m [38;5;124;03mavailable for recommendation.[39;00m
[0;32m   (...)[0m
[1;32m     20[0m [38;5;124;03m    co_clustering.CoClustering[39;00m
[1;32m     21[0m [38;5;124;03m"""[39;00m
[0;32m---> 23[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01malgo_base[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m AlgoBase
[1;32m     24[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mbaseline_only[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m BaselineOnly
[1;32m     25[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mco_clustering[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m CoClustering

File [0;32m/usr/local/lib/python3.10/site-packages/surprise/prediction_algorithms/algo_base.py:8[0m
[1;32m      1[0m [38;5;124;03m"""[39;00m
[1;32m      2[0m [38;5;124;03mThe :mod:`surprise.prediction_algorithms.algo_base` module defines the base[39;00m
[1;32m      3[0m [38;5;124;03mclass :class:`AlgoBase` from which every single prediction algorithm has to[39;00m
[1;32m      4[0m [38;5;124;03minherit.[39;00m
[1;32m      5[0m [38;5;124;03m"""[39;00m
[1;32m      6[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mheapq[39;00m
[0;32m----> 8[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01m.[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m similarities [38;5;28;01mas[39;00m sims
[1;32m      9[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01moptimize_baselines[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m baseline_als, baseline_sgd
[1;32m     10[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01m.[39;00m[38;5;21;01mpredictions[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Prediction, PredictionImpossible

File [0;32m/usr/local/lib/python3.10/site-packages/surprise/similarities.pyx:1[0m, in [0;36minit surprise.similarities[0;34m()[0m

[0;31mImportError[0m: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

